name: openapm

services:
  db:
    image: postgres:15-alpine
    platform: linux/amd64
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3

  backend:
    image: openapm/backend:latest
    platform: linux/amd64
    build:
      context: ./server
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5050:5050"
    environment:
      - POSTGRES_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
      - DEBUG=true
    volumes:
      - ./server/app/:/app/app/
    command: >
      sh -c "python app/db.py
      && uvicorn app.main:app --reload --host 0.0.0.0 --port 5050 --proxy-headers --use-colors --log-level info"
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:5050/status"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
